export { default as About } from './About'
export { default as Benefits } from './Benefits'
export { default as Contact } from './Contact'
export { default as Header } from './Header'
export { default as Navbar } from './Navbar'